stop_chars = {',', '\'', '"', ':', '-', '?', '!', '&', '+', '#', '@', '/',
					'\\', '(', ')', '{', '}', '%', '^', '*', '_'}
stop_words = {'a','in', 's', 'do', 'that', 'between', 'most', 'who', 'their',
'now', 'be', 'which', 'ourselves', 'my', 'some', 'of', 'the', 'to', 'hasn',
'about', 'was', 'before', 'its', 'but', 'with', 'have', 'on', 'own', 'ma',
'them', 'doesn', 'mustn', 'a', 'same', 'yourself', 'y', 'is', 'for', 'where',
'aren', 'had', 'didn', 'o', 'this', 'himself', 'in', 'further', 'only', 'against',
't', 'each', 'as', 'i', 'just', 'if', 'out', 'were', 'from', 'has', 'again',
 'through', 'we', 'how', 'me', 'so', 'does', 'off', 'yourselves', 'you', 'below',
  'wasn', 'been', 'because', 'any', 'am', 'will', 're', 'ain', 'during', 'or',
   'than', 'your', 'when', 'these', 'wouldn', 'll', 'haven', 'itself', 'more',
	'she', 'while', 'yours', 'by', 'both', 'couldn', 'his', 'at', 'down', 've',
	 'mightn', 'and', 'after', 'then', 'theirs', 'it', 'such', 'our', 'those',
	  'don', 'what', 'he', 'themselves', 'd', 'whom', 'him', 'above', 'ours',
	   'once', 'can', 'weren', 'under', 'not', 'there', 'here', 'shan', 'why',
		'being', 'they', 'm', 'won', 'into', 'over', 'up', 'needn', 'few', 'isn',
		 'are', 'shouldn', 'too', 'hadn', 'myself', 'did', 'her', 'having', 'very',
		  'herself', 'doing', 'hers', 'should', 'no', 'all', 'nor', 'an', 'other',
		   'until', 'also', 'someone', 'anyone'}